apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: arrive-demo-azure-virtualnetwork
spec:
  providerConfigRef:
    name: 'azure-default-providerconfig'
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: West Europe
    resourceGroupName: 'mia-demo'
